[package]
name = "cbp-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.17"
async-graphql-poem = "7.0.17"
criterion = "0.7.0"
poem = "3.1.12"
slab = "0.4.11"
tokio = {version = "1.48.0", features = ["rt-multi-thread", "macros"] }
binance-sdk = { version = "1.0.0", features = ["spot"] }