[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "template"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-docs = "mkdocs build"

