[workspace]
name = "cbp"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]

[dependencies]
python = "3.14.*"
# cmake = "*"
# ninja = "*"
# rust = "*"
# go = "*"
# nodejs = "*"
# wasm-pack = "*"

[pypi-dependencies]
cbp-fastapi = { path = "runtimes/python/src/cbp_fastapi", editable = true }
# cbp-hyperliquid = { path = "python/src/pkg2", editable = true }

[tasks]
# Python
build-cbp-fastapi = { cmd = "uv build", cwd = "runtimes/python/src/cbp_fastapi" }
run-cbp-fastapi = { cmd = "strawberry dev app", cwd = "runtimes/python/src/cbp_fastapi" }
# py-test-cbp-hyperliquid = { cmd = "pytest", cwd = "runtimes/python/src/hyperliquid" }

# # C++
# cpp-configure-pkg1 = { cmd = "cmake -S . -B build -G Ninja", cwd = "cpp/src/pkg1" }
# cpp-build-pkg1 = { cmd = "cmake --build build", cwd = "cpp/src/pkg1", depends-on = ["cpp-configure-pkg1"] }
# # Repeat for pkg2

# # Rust
# rust-build-pkg1 = { cmd = "cargo build", cwd = "rust/src/pkg1" }
# rust-test-pkg1 = { cmd = "cargo test", cwd = "rust/src/pkg1" }
# # Repeat

# # Go
# go-build-pkg1 = { cmd = "go build ./...", cwd = "go/src/pkg1" }
# go-test-pkg1 = { cmd = "go test ./...", cwd = "go/src/pkg1" }
# # Repeat

# # Node.js
# node-install-pkg1 = { cmd = "npm install", cwd = "nodejs/src/pkg1" }
# node-build-pkg1 = { cmd = "npm run build", cwd = "nodejs/src/pkg1", depends-on = ["node-install-pkg1"] }
# # Repeat

# # Wasm (Rust-based)
# wasm-build-pkg1 = { cmd = "wasm-pack build --release", cwd = "wasm/src/pkg1" }
# # Repeat

# # Bash (example)
# bash-run-pkg1 = { cmd = "./run.sh", cwd = "bash/src/pkg1" }
# # Repeat

# build-all = { depends-on = ["py-build-cbp-fastapi", "cpp-build-hyperliquid"] }  # List all build tasks
