[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://prefix.dev/pixi-build-backends", "https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
cbp = { path = "." }

[tasks]
hello = "echo Hello, World!"


[package]
name = "cbp"
version = "0.0.1"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
python = ">=3.14.0,<3.15"
typer = ">=0.20.0,<0.21"
copier = ">=9.10.3,<10"
mkdocs = ">=1.6.1,<2"

