[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "base"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
copier = ">=9.10.3,<10"

[pypi-dependencies]
copier-template-extensions = ">=0.3.3, <0.4"
