[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cbp"
version = "0.1.0"
dependencies = [
    "python>=3.14.0,<3.15",
    "typer>=0.20.0,<0.21",
    "copier>=9.10.3,<10",
    "mkdocs>=1.6.1,<2"
]