// graphql_gen.rs
// Add this to your crate (e.g. lib.rs or a dedicated module)

use std::collections::HashMap;

/// Input: one or more lines of your desired Rust-like type definitions
/// Output: ready-to-use async-graphql Rust code with modules and SimpleObjects
pub fn generate_async_graphql(input: impl AsRef<str>) -> String {
    let src = input.as_ref();
    let structs = parse_structs(src);
    let mut output = vec![
        "// This file is auto-generated by generate_async_graphql()".to_string(),
        "use async_graphql::*;".to_string(),
        "".to_string(),
    ];

    for (mod_path, structs_in_mod) in structs {
        if !mod_path.is_empty() {
            let depth = mod_path.split("::").count() - 1;
            let indent = "    ".repeat(depth);
            output.push(format!("{}pub mod {} {{", indent, mod_path.split("::").last().unwrap()));
        }

        for (name, fields) in structs_in_mod {
            output.push(format!("    #[derive(SimpleObject, Clone, Debug)]"));
            output.push(format!("    pub struct {} {{", name));
            for (field_name, rust_type) in fields {
                let gql_type = to_gql_type(&rust_type);
                let rust_field = if ["type", "async", "mut", "box"].contains(&field_name.as_str()) {
                    format!("r#{}", field_name)
                } else {
                    field_name.clone()
                };
                output.push(format!("        #[graphql(name = \"{}\")]", field_name));
                output.push(format!("        pub {}: {},", rust_field, gql_type));
            }
            output.push("    }\n".to_string());
        }

        if !mod_path.is_empty() {
            let depth = mod_path.split("::").count() - 1;
            let indent = "    ".repeat(depth);
            output.push(format!("{}}}", indent));
            output.push("".to_string());
        }
    }

    output.join("\n")
}

fn to_gql_type(t: &str) -> String {
    let t = t.trim();
    if t.starts_with("Vec<") && t.ends_with('>') {
        let inner = &t[4..t.len()-1];
        format!("Vec<{}>", to_gql_type(inner))
    } else if t.starts_with("Option<") && t.ends_with('>') {
        let inner = &t[7..t.len()-1];
        format!("Option<{}>", to_gql_type(inner))
    } else {
        match t {
            "String" => "String".to_string(),
            "i32" | "i64" | "f64" | "bool" => t.to_string(),
            _ => t.to_string(), // custom type like Symbol, Filter, etc.
        }
    }
}

type ModulePath = String;
type StructName = String;
type FieldMap = HashMap<String, String>;

fn parse_structs(src: &str) -> HashMap<ModulePath, Vec<(StructName, FieldMap)>> {
    let mut modules: HashMap<String, Vec<(String, FieldMap)>> = HashMap::new();
    let mut current_mod = String::new();
    let mut brace_level = 0;
    let mut current_struct = None::<(String, FieldMap)>;

    for line in src.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") { continue; }

        if line.starts_with("mod ") {
            let name = line[4..].trim_end_matches(['{', ' ']).trim();
            if !current_mod.is_empty() {
                current_mod.push_str("::");
            }
            current_mod.push_str(name);
            brace_level += 1;
            continue;
        }

        if line.contains('{') {
            brace_level += line.matches('{').count();
            if let Some(name) = line.split('{').next() {
                let name = name.trim();
                if !name.is_empty() && !name.starts_with("mod") {
                    current_struct = Some((name.to_string(), HashMap::new()));
                }
            }
        }

        if line.contains('}') {
            brace_level -= line.matches('}').count();
            if brace_level == 0 && !current_mod.is_empty() {
                current_mod.clear();
            }
            if let Some((name, fields)) = current_struct.take() {
                modules.entry(current_mod.clone())
                    .or_default()
                    .push((name, fields));
            }
        }

        if let Some((_, fields)) = &mut current_struct {
            if line.contains(':') && !line.contains('{') && !line.contains('}') {
                let parts: Vec<&str> = line.splitn(2, ':').collect();
                if parts.len() == 2 {
                    let field = parts[0].trim().to_string();
                    let typ = parts[1].trim().trim_end_matches(',').trim().to_string();
                    fields.insert(field, typ);
                }
            }
        }
    }

    modules
}

// Example usage:
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate() {
        let input = r#"
        mod binance {
            ExchangeInfo {
                timezone: String,
                serverTime: i64,
                symbols: Vec<Symbol>,
            }

            Symbol {
                symbol: String,
                baseAsset: String,
                quoteAsset: String,
                pricePrecision: i32,
                filters: Vec<Filter>,
            }

            Filter {
                filterType: String,
                minPrice: Option<String>,
                maxQty: Option<String>,
            }
        }
        "#;

        let rs_code = generate_async_graphql(input);
        println!("{}", rs_code);
        // → outputs perfectly nested pub mod binance { ... with SimpleObject structs
    }
}