[workspace]
name = "cbp-rust"
version = "0.1.0"
description = "Component Based Programming ~ Rust"
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
rust = ">=1.91.1,<1.92"
rust-src = ">=1.91.1,<2"
openssl = ">=3.6.0,<4"
clang = ">=21.1.6,<22"
clang-tools = ">=21.1.6,<22"

[tasks]

start = "cargo run"
test = "cargo test --workspace"
clean = "cargo clean"
fmt = "cargo fmt -- --check"
lint = { cmd = "cargo clippy --workspace -- -D warnings", depends-on = ["fmt"] }

[tasks.add]
args = [{"arg" = "rust_package"},{ "arg" = "features", default = ""}]
cmd = "cargo add {arg} {features}||cargo add {arg} {features} --pypi"

[tasks.build]
cmd = "cargo build --release --workspace |& tee build.log"
env = {CC = "clang", CXX = "clang++", CARGO_TARGET_X86_64_CONDA_LINUX_GNU_LINKER = "clang", CFLAGS = "-fuse-ld=lld", CXXFLAGS = "-fuse-ld=lld"}




