#!/usr/bin/env python3
"""
Binance Rust OpenAPI Client → async-graphql Schema Generator

Converts all *_api.rs files (generated by openapi-generator) into a clean,
modular async-graphql setup with proper Query and Mutation objects.

Features:
- Correctly parses multi-line function signatures
- Distinguishes GET (Query) vs POST/PUT/DELETE (Mutation)
- Generates safe Rust identifiers and clean GraphQL names
- Outputs modular files: query.rs, mutation.rs, schema.rs, mod.rs
- Injects BinanceClient via context.data<Arc<BinanceClient>>

Usage:
    python scripts/rs2gql.py <input_dir> <output_dir>

Example:
    python scripts/rs2gql.py src/binance/out/rust/src/apis src/graphql

Output:
    src/graphql/
    ├── mod.rs
    ├── query.rs        ← all GET endpoints
    ├── mutation.rs     ← all POST/PUT/DELETE endpoints
    └── schema.rs       ← Schema builder with client injection

In your main.rs or lib.rs:
    pub mod graphql;
    use graphql::create_schema;
    use std::sync::Arc;

    let client = Arc::new(BinanceClient::new(...));
    let schema = create_schema(client);
"""

import typer
import re
from pathlib import Path

app = typer.Typer(
    name="rs2gql", help="Convert Binance Rust API files → async-graphql schema")


FIELD_TEMPLATE = """    #[graphql(name = "{gql_name}")]
    async fn {field_name}(
        &self,
        ctx: &Context<'_>{args}
    ) -> FieldResult<{return_type}> {{
        let client = ctx.data_unchecked::<std::sync::Arc<BinanceClient>>();
        binance::{module}::{func_name}(
            &client.config(){call_args}
        ).await
        .map_err(|e| async_graphql::Error::new(e.to_string()))
    }}"""


def to_gql_name(name: str) -> str:
    """Convert sapi_v1_asset_get_balance_get → getAssetBalance"""
    name = re.sub(r"^(sapi_|fapi_|dapi_|api_)(v\d_)?", "", name)
    name = re.sub(r"_(get|post|put|patch|delete$", "", name, flags=re.I)
    name = re.sub(r"_([a-z0-9])", lambda m: m.group(1).upper(), name)
    return name[0].lower() + name[1:] if name else "unknown"


def rust_to_gql_type(t: str) -> str:
    mapping = {
        "i64": "i64", "i32": "i32", "f64": "f64", "f32": "f32",
        "&str": "String", "String": "String",
    }
    return mapping.get(t.strip("& "), t)


@app.command()
def convert(
    input_dir: Path = typer.Argument(..., help="Directory containing *_api.rs files (e.g. src/apis)"),
    output_dir: Path = typer.Argument(..., help="Where to generate graphql/ module (e.g.g. src/graphql)"),
):
    """Generate async-graphql Query + Mutation from Binance Rust API files."""

    if not input_dir.is_dir():
        typer.echo(f"Error: '{input_dir}' is not a directory", err=True)
        raise typer.Exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    query_fields = []
    mutation_fields = []

    for api_file in sorted(input_dir.glob("*_api.rs")):
        lines = api_file.read_text().splitlines()
        module = api_file.stem

        i = 0
        while i < len(lines):
            line = lines[i]

            if not line.strip().startswith("pub async fn "):
                i += 1
                continue

            # Extract function name
            m = re.search(r"pub async fn (\w+)", line)
            if not m:
                i += 1
                continue
            func_name = m.group(1)

            # Reconstruct full signature
            signature = line
            start_i = i
            i += 1
            while i < len(lines) and not lines[i].strip().endswith(")"):
                signature += " " + lines[i].strip()
                i += 1
            if i < len(lines) and ")" in lines[i]:
                signature += " " + lines[i].strip()
                i += 1

            # Extract parameters (skip configuration)
            params_match = re.search(r"\((.*)\)", signature, re.DOTALL)
            if not params_match:
                continue

            raw_params = [
                p.strip()
                for p in params_match.group(1).split(",")
                if p.strip() and "configuration:" not in p
            ]

            args = []
            call_args = []
            for p in raw_params:
                if ":" not in p:
                    continue
                name_part, type_part = p.split(":", 1)
                name = name_part.strip().lstrip("&")
                t = type_part.strip()

                is_opt = t.startswith("Option<")
                clean_t = t[7:-1].strip("& ") if is_opt else t.strip("& ")
                gql_t = rust_to_gql_type(clean_t)

                if is_opt:
                    args.append(f", {name}: Option<{gql_t}>")
                    call_args.append(f"{name}.unwrap_or_default()")
                else:
                    args.append(f", {name}: {gql_t}")
                    call_args.append(name)

            # Detect if it's a mutation
            snippet = "\n".join(lines[start_i:start_i + 40])
            is_mutation = any(
                k in snippet for k in ["POST", "PUT", "PATCH", "DELETE", ".post(", ".put(", ".delete("]
            )

            gql_name = to_gql_name(func_name)
            field_name = re.sub(r"\W+", "_", gql_name)
            return_type = "".join(
                w.capitalize() for w in func_name.split("_")
                if w not in {"sapi", "v1", "v2", "fapi, "get", "post", "put", "delete"}
            ) + "Response"

            call_args_str = ",\n            ".join([""] + call_args) if call_args else ""

            field = FIELD_TEMPLATE.format(
                gql_name=gql_name,
                field_name=field_name,
                args="".join(args),
                return_type=return_type,
                module=module,
                func_name=func_name,
                call_args=call_args_str,
            )

            if is_mutation:
                mutation_fields.append(field)
            else:
                query_fields.append(field)

    # Write all files
    (output_dir / "query.rs").write_text(f"""use async_graphql::{{Context, FieldResult, Object}};

pub struct Query;

#[Object]
impl Query {{
{"\n\n".join(query_fields)}
}}
""")

    (output_dir / "mutation.rs").write_text(f"""use async_graphql::{{Context, FieldResult, Object}};

pub struct Mutation;

#[Object]
impl Mutation {{
{"\n\n".join(mutation_fields)}
}}
""")

    (output_dir / "schema.rs").write_text("""use async_graphql::{{EmptySubscription, Schema}};
use std::sync::Arc;

pub use query::Query;
pub use mutation::Mutation;

mod query;
mod mutation;

pub type AppSchema = Schema<Query, Mutation, EmptySubscription>;

pub fn create_schema(client: Arc<BinanceClient>) -> AppSchema {
    Schema::build(Query, Mutation, EmptySubscription)
        .data(client)
        .finish()
}
""")

    (output_dir / "mod.rs").write_text("pub mod query;\npub mod mutation;\npub mod schema;\n")

    typer.secho(
        f"Success! Generated {len(query_fields)} queries + {len(mutation_fields)} mutations",
        fg=typer.colors.GREEN,
        bold=True,
    )
    typer.secho(f"→ {output_dir.resolve()}", fg=typer.colors.CYAN)


if __name__ == "__main__":
    app()
