#!/usr/bin/env python3
"""
rust_models_to_async_graphql.py

Converts real OpenAPI-generated Rust model files (like from binance-connector-rust)
into clean, correct async-graphql SimpleObject types.

Handles:
- /* ... */ doc headers
- #[derive(...)]
- #[serde(rename = "...")]
- Option<T>, Vec<T>
- Nested types
- Reserved keywords

Usage:
    python rust_models_to_async_graphql.py path/to/*.rs > gql_models.rs
"""

import re
import sys
from pathlib import Path
from typing import List, Tuple, Dict


def clean_content(content: str) -> str:
    """Skip file header comments until actual Rust code starts"""
    lines = content.splitlines()
    cleaned = []
    started = False
    for line in lines:
        stripped = line.strip()
        if not started and (stripped.startswith(("use ", "pub struct", "#[", "mod ", "//", "/*"))):
            if stripped.startswith("pub struct") or stripped.startswith("#["):
                started = True
            # Keep doc comments and attributes
            if not stripped.startswith("/*"):
                cleaned.append(line)
        elif started:
            cleaned.append(line)
    return "\n".join(cleaned)


def extract_structs(content: str) -> List[Tuple[str, Dict[str, str]]]:
    """Extract struct name and its fields with correct GraphQL names"""
    content = clean_content(content)
    structs = []

    # Find all `pub struct Name { ... }`
    for match in re.finditer(r"pub\s+struct\s+(\w+)", content):
        struct_name = match.group(1)
        start_pos = match.start()

        # Find opening brace
        brace_start = content.find("{", start_pos)
        if brace_start == -1:
            continue

        # Count braces to find closing one
        brace_count = 1
        i = brace_start + 1
        while i < len(content) and brace_count > 0:
            if content[i] == '{':
                brace_count += 1
            elif content[i] == '}':
                brace_count -= 1
            i += 1

        body = content[brace_start + 1:i - 1]
        fields: Dict[str, str] = {}

        # First: fields with #[serde(rename = "...")]
        for m in re.finditer(r'#\[serde\(rename\s*=\s*"([^"]+)"[^]]*\]\)\s*pub\s+(\w+)\s*:\s*([^,\n]+)', body):
            gql_name, _rust_name, typ = m.groups()
            fields[gql_name] = typ.strip()

        # Then: fields without rename (use Rust name as GraphQL name)
        for m in re.finditer(r'pub\s+(\w+)\s*:\s*([^,\n]+)', body):
            rust_name, typ = m.groups()
            if rust_name not in fields.values():  # avoid duplicate if renamed
                fields[rust_name] = typ.strip()

        structs.append((struct_name, fields))

    return structs


def rust_to_gql_type(rust_type: str) -> str:
    """Convert Rust type to async-graphql type"""
    t = rust_type.strip()

    # Handle Vec<T>
    if t.startswith("Vec<"):
        inner = t[4:-1]
        return f"Vec<{rust_to_gql_type(inner)}>"

    # Handle Option<T>
    if t.startswith("Option<"):
        inner = t[7:-1]
        return f"Option<{rust_to_gql_type(inner)}>"

    # Common mappings
    mapping = {
        "String": "String",
        "i64": "i64",
        "i32": "i32",
        "f64": "f64",
        "bool": "bool",
    }

    # Extract last part of path::to::Type
    base = t.split("::").pop()
    return mapping.get(base, base)  # fallback to type name (e.g. Symbol, Filter)


def generate_gql_code(structs: List[Tuple[str, Dict[str, str]]]) -> str:
    lines = [
        "// <auto-generated> async-graphql models from binance-connector-rust",
        "// Do not edit manually — regenerate with rust_models_to_async_graphql.py",
        "",
        "use async_graphql::*;",
        "",
        "pub mod binance_models {",
    ]

    for struct_name, fields in structs:
        lines.append(f"    #[derive(SimpleObject, Clone, Debug)]")
        lines.append(f"    pub struct {struct_name} {{")

        for gql_name, rust_type in fields.items():
            gql_type = rust_to_gql_type(rust_type)
            rust_field_name = f"r#{gql_name}" if gql_name in {"type", "async", "mut", "box"} else gql_name
            lines.append(f'        #[graphql(name = "{gql_name}")]')
            lines.append(f"        pub {rust_field_name}: {gql_type},")

        lines.append("    }\n")

    lines.append("}")
    return "\n".join(lines)


def main(paths: List[str]):
    all_structs = []
    for path_str in paths:
        path = Path(path_str)
        if not path.exists():
            print(f"File not found: {path}", file=sys.stderr)
            continue
        content = path.read_text()
        structs = extract_structs(content)
        all_structs.extend(structs)

    if not all_structs:
        print("No structs found in provided files.", file=sys.stderr)
        sys.exit(1)

    print(generate_gql_code(all_structs))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python rust_models_to_async_graphql.py <file1.rs> <file2.rs> ...")
        sys.exit(1)
    main(sys.argv[1:])