[project]
name = "cbp_fastapi"  # Optional, for clarity
version = "0.1.0"
channels = ["conda-forge"]
platforms = []

[dependencies]
rich = "*"

[pypi-dependencies]
fastapi = { version = "*", extras = ["standard"] }
# some-conda-package = "*"
# # Add more conda packages here, e.g.
# numpy = "*"
# scipy = "*"

# # Optional: dev dependencies
# [feature.dev.dependencies]
# pytest = "*"