#!/usr/bin/env python3
"""
rust_models_to_async_graphql.py

Generates *_agql.rs + mod.rs from binance-connector-rust models.
"""

import re
import sys
import argparse
from pathlib import Path
from typing import List, Tuple, Dict


def extract_structs(content: str) -> List[Tuple[str, Dict[str, str]]]:
    structs = []
    content = content.replace("\r\n", "\n")
    i = 0

    while i < len(content):
        m = re.search(r"pub\s+struct\s+(\w+)", content[i:])
        if not m:
            break
        struct_name = m.group(1)
        abs_pos = i + m.end()
        brace_pos = content.find("{", abs_pos)
        if brace_pos == -1:
            break

        depth = 1
        end = brace_pos + 1
        while end < len(content) and depth > 0:
            if content[end] == '{':
                depth += 1
            elif content[end] == '}':
                depth -= 1
            end += 1

        body = content[brace_pos + 1:end - 1]
        fields: Dict[str, str] = {}

        for m in re.finditer(r'#\[serde\([^)]*rename\s*=\s*"([^"]+)"[^)]*\]\)\s*pub\s+(\w+)\s*:\s*([^,\n]+)', body):
            gql_name, _, typ = m.groups()
            fields[gql_name] = typ.strip()

        for m in re.finditer(r'pub\s+(\w+)\s*:\s*([^,\n]+)', body):
            rust_name, typ = m.groups()
            if rust_name not in fields:
                fields[rust_name] = typ.strip()

        structs.append((struct_name, fields))
        i = end

    return structs


def rust_to_gql_type(t: str) -> str:
    t = t.strip()
    if t.startswith("Vec<"):
        return f"Vec<{rust_to_gql_type(t[4:-1])}>"
    if t.startswith("Option<"):
        return f"Option<{rust_to_gql_type(t[7:-1])}>"
    base = t.split("::")[-1]
    return {
        "String": "String", "i64": "i64", "i32": "i32",
        "f64": "f64", "bool": "bool", "u64": "i64", "u32": "i32",
    }.get(base, base)


def generate_model_file(structs: List[Tuple[str, Dict[str, str]]]) -> str:
    lines = [
        "// <auto-generated> async-graphql model",
        "// DO NOT EDIT – regenerated from original model",
        "",
        "#![allow(dead_code, unused_imports, non_camel_case_types)]",
        "",
        "use async_graphql::*;",
        "",
        "pub mod binance_models {",
    ]

    for name, fields in sorted(structs, key=lambda x: x[0]):
        if not fields:
            continue
        lines.append(f"    #[derive(SimpleObject, Clone, Debug)]")
        lines.append(f"    pub struct {name} {{")
        for gql_name in sorted(fields):
            typ = fields[gql_name]
            gql_type = rust_to_gql_type(typ)
            field_name = f"r#{gql_name}" if gql_name in {"type", "async", "box", "self", "mut"} else gql_name
            lines.append(f'        #[graphql(name = "{gql_name}")]')
            lines.append(f"        pub {field_name}: {gql_type},")
        lines.append("    }\n")

    lines.append("}")
    return "\n".join(lines)


def generate_mod_rs(output_files: List[Path]) -> str:
    lines = [
        "// <auto-generated>",
        "// Re-exports all async-graphql models",
        "// Update by re-running rust_models_to_async_graphql.py",
        "",
    ]

    for file in sorted(output_files):
        module_name = file.stem
        lines.append(f"pub mod {module_name};")
        lines.append(f"pub use {module_name}::binance_models::*;")
        lines.append("")

    return "\n".join(lines)


def collect_input_paths(inputs: List[str]) -> List[Path]:
    paths = []
    for item in inputs:
        p = Path(item).expanduser().resolve()
        if p.is_dir():
            paths.extend(p.rglob("*.rs"))
        elif p.is_file() and p.suffix == ".rs":
            paths.append(p)
        else:
            try:
                matches = list(Path(".").glob(item))
                paths.extend(m for m in matches if m.is_file() and m.suffix == ".rs")
            except Exception:
                print(f"Warning: '{item}' not found or invalid", file=sys.stderr)
    return sorted(set(paths))


def main():
    parser = argparse.ArgumentParser(
        description="Generate async-graphql models + mod.rs from binance-connector-rust"
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        help="Files, globs, or directories (recursive, absolute paths OK)"
    )
    parser.add_argument(
        "-d", "--output-dir",
        type=Path,
        required=True,
        help="Output directory"
    )

    args = parser.parse_args()

    output_dir: Path = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    input_paths = collect_input_paths(args.inputs)

    if not input_paths:
        print("No .rs files found in inputs.", file=sys.stderr)
        sys.exit(1)

    generated_files = []

    for input_path in input_paths:
        try:
            content = input_path.read_text()
            structs = extract_structs(content)
            if not structs:
                continue

            output_file = output_dir / f"{input_path.stem}_agql.rs"
            code = generate_model_file(structs)
            output_file.write_text(code)
            generated_files.append(output_file)
            print(f"{input_path.name} → {output_file.name}")
        except Exception as e:
            print(f"Failed {input_path}: {e}", file=sys.stderr)

    # Generate mod.rs
    mod_rs_path = output_dir / "mod.rs"
    mod_rs_path.write_text(generate_mod_rs(generated_files))

    print(f"\nSuccess! {len(generated_files)} model files + mod.rs generated in:\n   {output_dir}\n")


if __name__ == "__main__":
    main()