// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct AccountInformationResponse {
        #[graphql(name = "assets")]
        pub assets: Option<Vec<AccountInformationResponseAssetsInner>>,
        #[graphql(name = "can_deposit")]
        pub can_deposit: Option<bool>,
        #[graphql(name = "can_trade")]
        pub can_trade: Option<bool>,
        #[graphql(name = "can_withdraw")]
        pub can_withdraw: Option<bool>,
        #[graphql(name = "fee_tier")]
        pub fee_tier: Option<i64>,
        #[graphql(name = "positions")]
        pub positions: Option<Vec<AccountInformationResponsePositionsInner>>,
        #[graphql(name = "update_time")]
        pub update_time: Option<i64>,
    }

}