// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct BasisResponseInner {
        #[graphql(name = "annualized_basis_rate")]
        pub annualized_basis_rate: Option<String>,
        #[graphql(name = "basis")]
        pub basis: Option<String>,
        #[graphql(name = "basis_rate")]
        pub basis_rate: Option<String>,
        #[graphql(name = "contract_type")]
        pub contract_type: Option<String>,
        #[graphql(name = "futures_price")]
        pub futures_price: Option<String>,
        #[graphql(name = "index_price")]
        pub index_price: Option<String>,
        #[graphql(name = "pair")]
        pub pair: Option<String>,
        #[graphql(name = "timestamp")]
        pub timestamp: Option<i64>,
    }

}