// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct ChangePositionModeResponse {
        #[graphql(name = "code")]
        pub code: Option<i64>,
        #[graphql(name = "msg")]
        pub msg: Option<String>,
    }

}