// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct ChangeInitialLeverageResponse {
        #[graphql(name = "leverage")]
        pub leverage: Option<i64>,
        #[graphql(name = "max_qty")]
        pub max_qty: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
    }

}