// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct ExchangeInformationResponseSymbolsInnerFiltersInner {
        #[graphql(name = "filter_type")]
        pub filter_type: Option<String>,
        #[graphql(name = "limit")]
        pub limit: Option<i64>,
        #[graphql(name = "max_price")]
        pub max_price: Option<String>,
        #[graphql(name = "max_qty")]
        pub max_qty: Option<String>,
        #[graphql(name = "min_price")]
        pub min_price: Option<String>,
        #[graphql(name = "min_qty")]
        pub min_qty: Option<String>,
        #[graphql(name = "multiplier_decimal")]
        pub multiplier_decimal: Option<String>,
        #[graphql(name = "multiplier_down")]
        pub multiplier_down: Option<String>,
        #[graphql(name = "multiplier_up")]
        pub multiplier_up: Option<String>,
        #[graphql(name = "step_size")]
        pub step_size: Option<String>,
        #[graphql(name = "tick_size")]
        pub tick_size: Option<String>,
    }

}