// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct FuturesAccountBalanceResponseInner {
        #[graphql(name = "account_alias")]
        pub account_alias: Option<String>,
        #[graphql(name = "asset")]
        pub asset: Option<String>,
        #[graphql(name = "available_balance")]
        pub available_balance: Option<String>,
        #[graphql(name = "balance")]
        pub balance: Option<String>,
        #[graphql(name = "cross_un_pnl")]
        pub cross_un_pnl: Option<String>,
        #[graphql(name = "cross_wallet_balance")]
        pub cross_wallet_balance: Option<String>,
        #[graphql(name = "update_time")]
        pub update_time: Option<i64>,
        #[graphql(name = "withdraw_available")]
        pub withdraw_available: Option<String>,
    }

}