// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct GetOrderModifyHistoryResponseInner {
        #[graphql(name = "amendment")]
        pub amendment: Option<GetOrderModifyHistoryResponseInnerAmendment>>,
        #[graphql(name = "amendment_id")]
        pub amendment_id: Option<i64>,
        #[graphql(name = "client_order_id")]
        pub client_order_id: Option<String>,
        #[graphql(name = "order_id")]
        pub order_id: Option<i64>,
        #[graphql(name = "pair")]
        pub pair: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
        #[graphql(name = "time")]
        pub time: Option<i64>,
    }

}