// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct GetPositionMarginChangeHistoryResponseInner {
        #[graphql(name = "amount")]
        pub amount: Option<String>,
        #[graphql(name = "asset")]
        pub asset: Option<String>,
        #[graphql(name = "position_side")]
        pub position_side: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
        #[graphql(name = "time")]
        pub time: Option<i64>,
    }

}