// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct GetOrderModifyHistoryResponseInnerAmendment {
        #[graphql(name = "count")]
        pub count: Option<i64>,
        #[graphql(name = "orig_qty")]
        pub orig_qty: Option<GetOrderModifyHistoryResponseInnerAmendmentOrigQty>>,
        #[graphql(name = "price")]
        pub price: Option<GetOrderModifyHistoryResponseInnerAmendmentPrice>>,
    }

}