// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct LongShortRatioResponseInner {
        #[graphql(name = "long_account")]
        pub long_account: Option<String>,
        #[graphql(name = "long_short_ratio")]
        pub long_short_ratio: Option<String>,
        #[graphql(name = "pair")]
        pub pair: Option<String>,
        #[graphql(name = "short_account")]
        pub short_account: Option<String>,
        #[graphql(name = "timestamp")]
        pub timestamp: Option<i64>,
    }

}