// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct NotionalBracketForPairResponseInnerBracketsInner {
        #[graphql(name = "bracket")]
        pub bracket: Option<i64>,
        #[graphql(name = "cum")]
        pub cum: Option<Decimal>,
        #[graphql(name = "initial_leverage")]
        pub initial_leverage: Option<i64>,
        #[graphql(name = "maint_margin_ratio")]
        pub maint_margin_ratio: Option<Decimal>,
        #[graphql(name = "qty_cap")]
        pub qty_cap: Option<i64>,
        #[graphql(name = "qtyl_floor")]
        pub qtyl_floor: Option<i64>,
    }

}