// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct OpenInterestResponse {
        #[graphql(name = "contract_type")]
        pub contract_type: Option<String>,
        #[graphql(name = "open_interest")]
        pub open_interest: Option<String>,
        #[graphql(name = "pair")]
        pub pair: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
        #[graphql(name = "time")]
        pub time: Option<i64>,
    }

}