// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct PositionInformationResponseInner {
        #[graphql(name = "break_even_price")]
        pub break_even_price: Option<String>,
        #[graphql(name = "entry_price")]
        pub entry_price: Option<String>,
        #[graphql(name = "is_auto_add_margin")]
        pub is_auto_add_margin: Option<String>,
        #[graphql(name = "isolated_margin")]
        pub isolated_margin: Option<String>,
        #[graphql(name = "leverage")]
        pub leverage: Option<String>,
        #[graphql(name = "liquidation_price")]
        pub liquidation_price: Option<String>,
        #[graphql(name = "margin_type")]
        pub margin_type: Option<String>,
        #[graphql(name = "mark_price")]
        pub mark_price: Option<String>,
        #[graphql(name = "max_qty")]
        pub max_qty: Option<String>,
        #[graphql(name = "position_amt")]
        pub position_amt: Option<String>,
        #[graphql(name = "position_side")]
        pub position_side: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
        #[graphql(name = "un_realized_profit")]
        pub un_realized_profit: Option<String>,
        #[graphql(name = "update_time")]
        pub update_time: Option<i64>,
    }

}