// <auto-generated> async-graphql model
// DO NOT EDIT – regenerated from original model

#![allow(dead_code, unused_imports, non_camel_case_types)]

use async_graphql::*;

pub mod binance_models {
    #[derive(SimpleObject, Clone, Debug)]
    pub struct QueryCurrentOpenOrderResponse {
        #[graphql(name = "activate_price")]
        pub activate_price: Option<String>,
        #[graphql(name = "avg_price")]
        pub avg_price: Option<String>,
        #[graphql(name = "client_order_id")]
        pub client_order_id: Option<String>,
        #[graphql(name = "close_position")]
        pub close_position: Option<bool>,
        #[graphql(name = "cum_base")]
        pub cum_base: Option<String>,
        #[graphql(name = "executed_qty")]
        pub executed_qty: Option<String>,
        #[graphql(name = "order_id")]
        pub order_id: Option<i64>,
        #[graphql(name = "orig_qty")]
        pub orig_qty: Option<String>,
        #[graphql(name = "orig_type")]
        pub orig_type: Option<String>,
        #[graphql(name = "pair")]
        pub pair: Option<String>,
        #[graphql(name = "position_side")]
        pub position_side: Option<String>,
        #[graphql(name = "price")]
        pub price: Option<String>,
        #[graphql(name = "price_match")]
        pub price_match: Option<String>,
        #[graphql(name = "price_protect")]
        pub price_protect: Option<bool>,
        #[graphql(name = "price_rate")]
        pub price_rate: Option<String>,
        #[graphql(name = "reduce_only")]
        pub reduce_only: Option<bool>,
        #[graphql(name = "self_trade_prevention_mode")]
        pub self_trade_prevention_mode: Option<String>,
        #[graphql(name = "side")]
        pub side: Option<String>,
        #[graphql(name = "status")]
        pub status: Option<String>,
        #[graphql(name = "stop_price")]
        pub stop_price: Option<String>,
        #[graphql(name = "symbol")]
        pub symbol: Option<String>,
        #[graphql(name = "time")]
        pub time: Option<i64>,
        #[graphql(name = "time_in_force")]
        pub time_in_force: Option<String>,
        #[graphql(name = "update_time")]
        pub update_time: Option<i64>,
        #[graphql(name = "working_type")]
        pub working_type: Option<String>,
    }

}