[package]
name = "cbp-binance"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-graphql = "7.0.17"
async-graphql-poem = "7.0.17"
binance-sdk = { version = "1.0.0", features = ["spot"] }
poem = "3.1.12"
slab = "0.4.11"
tokio = { workspace = true, features = ["full"] }


# [target.x86_64-unknown-linux-gnu.cbp-binance]
# linker = "rust-lld"
