[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "cbp-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "fastapi run src/cbp_python/main.py"

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
fastapi = { version = ">=0.120.0, <0.121", extras = ["standard"] }
strawberry-graphql = { version = ">=0.284.1, <0.285", extras = ["fastapi"] }
